services:
  - type: web
    name: trends-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 app.py
    plan: free
    region: singapore
    envVars:
      - key: RENDER_PYTHON_VERSION
        value: 3.11.11
      - key: RENDER_PYTHON_PACKAGE_MANAGER
        value: pip
